//  export const SERVER_URL = "http://localhost:5000/"
 export const SERVER_URL = "http://143.244.150.181:5000/"
 export const PAIRS = [
    "BTCUSD",
    "ETHUSD",
    "BNBUSD",
    "XRPUSD",
    "DOGEUSD",
  "ADAUSD",
  "MATICUSD",
  "DOTUSD",
  "LTCUSD",
  "SOLUSD",
  "TRXUSD",
  "SHIBUSD",
  "UNIUSD",
  "AVAXUSD",
  "LINKUSD",
  "ATOMUSD",
  "XMRUSD",
  "XLMUSD",
  "ALGOUSD",
  "APEUSD",
  "XTZUSD",
  "AAVEUSD",
  "MANAUSD",
  "SANDUSD",
  "AXSUSD",
  "CAKEUSD",
  ]
